[phases.setup]
nixPkgs = [
  "nodejs_20",
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman",
  "fontconfig",
  "liberation_ttf",
  "noto-fonts-emoji"
]
nixLibs = [
  "cairo",
  "pango",
  "libjpeg",
  "giflib",
  "librsvg",
  "pixman"
]

[phases.install]
cmds = ["npm ci"]

[start]
cmd = "node src/index.js"

[variables]
FONTCONFIG_PATH = "/etc/fonts"
